version: '3.8'

services:
    dev:
        container_name: sever_shop_dev
        image: sever_shop_dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - "2020:2020"
        environment:
          DATABASE_URL: postgresql://postgres:123456@postgres:5432/postgres
          NODE_ENV: development
          PORT: 2020
        
    postgres:
        image: postgres:10.4
        ports:
            - "5432:5432"
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: postgres
       
